ekf_filter_node:
  ros__parameters:
    frequency: 30.0  # 滤波器更新频率/according IMU and GPS frequency
    sensor_timeout: 0.1  # 传感器数据超时时间/
    two_d_mode: false  # 是否限制为二维模式（false 表示三维）
    transform_time_offset: 0.0  # 坐标变换的时间偏移

    # 定义 EKF 的初始状态估计
    odom_frame: odom           # 输出的里程计坐标系
    base_link_frame: base_link # 机器人基座坐标系
    world_frame: map           # 全局坐标系

    # 配置 IMU 输入
    imu0: /imu/data
    imu0_config: [false, false, false,  # x, y, z 位置
                  false, false, true,   # roll, pitch, yaw 角度
                  false, false, false,  # x, y, z 速度
                  true,  true,  false,   # x, y, z 角速度
                  true,  true,  false]   # x, y, z 加速度
    imu0_differential: false  # 是否对 IMU 数据进行差分处理
    imu0_relative: false      # 是否将 IMU 数据视为相对值

    # 配置 GPS 输入
    gps0: /gps/fix
    gps0_config: [true,  true,  false,   # x, y, z 位置
                  false, false, false,  # roll, pitch, yaw 角度
                  false, false, false,  # x, y, z 速度
                  false, false, false,  # x, y, z 角速度
                  false, false, false]  # x, y, z 加速度
    gps0_differential: ture  # 是否对 GPS 数据进行差分处理
    gps0_relative:       # 是否将 GPS 数据视为相对值

    # 过程噪声协方差矩阵（可调）
    process_noise_covariance: [0.05, 0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0.05, 0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0.06, 0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
#从 x、y、z 开始的过程噪声协方差参数可以按如下思路调整：初始值建议：x = 0.05，y = 0.05，z = 0.06 若输出定位变化滞后或不敏感：适当增大这些值 若输出定位抖动较大：适当减小这些值
                                0,    0,    0,    1e-4, 0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    1e-4, 0,    0,     0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0.06, 0,     0,     0,    0,    0,    0,    0,    0,    0,

                                0,    0,    0,    0,    0,    0,    0.025, 0,     0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0.025, 0,    0,    0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     1e-4, 0,    0,    0,    0,    0,    0,
#初始设置： ẋ、ẏ：约 0.025 ż：约 0.06（二维应用可以不考虑 z 方向，或设置得更低） 调整方法： 根据车辆加减速情况及传感器测量噪声，通过实测数据逐步调整。 增大过程噪声让滤波器更快响应外界变化；减小则能平滑输出，但可能响应不足
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0.01, 0,    0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0.01, 0,    0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    1e-4, 0,    0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0.01, 0,    0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0.01, 0,
                                0,    0,    0,    0,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0,    1e-4]
#如果你的系统中加速度变化平稳且噪声较低，可以考虑设置一个较低的过程噪声值，例如 0.025～0.05。 如果加速度噪声较大或存在较多震动，建议设置一个较高的数值，比如 0.06～0.1。 如何根据实际情况调整滤波响应迟钝：如果发现系统对加速度变化响应不足，可能说明你设置的过程噪声太低，滤波器过于依赖预测模型，此时可以适当增加加速度对应的过程噪声。 滤波输出抖动大：如果加速度数据导致状态估计出现过大抖动，可能需要降低该部分的噪声值，增强预测模型的平滑效果。

    # 初始估计协方差矩阵（可调）
    initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                                  0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]
